package br.cadastrovendas.model;
// Generated Oct 4, 2012 3:51:06 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "PRODUTO")
public class Produto implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id_produto;
    @Column
    private String desc_produto;
    @Column
    private double valor_produto;

    public Produto() {
    }

    public Produto(String desc_produto) {
        this.desc_produto = desc_produto;
    }
    public int getId_produto() {
        return id_produto;
    }

    public void setId_produto(int id_produto) {
        this.id_produto = id_produto;
    }

    public String getDesc_Produto() {
        return desc_produto;
    }

    public void setDesc_Produto(String desc_produto) {
        this.desc_produto = desc_produto;
    }
    
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    public String getDesc_produto() {
        return desc_produto;
    }

    public void setDesc_produto(String desc_produto) {
        this.desc_produto = desc_produto;
    }

    public double getValor_produto() {
        return valor_produto;
    }

    public void setValor_produto(double valor_produto) {
        this.valor_produto = valor_produto;
    }
}
